"""add tables

Revision ID: 4fcba7695ea9
Revises: 6dca5ff20c43
Create Date: 2026-05-20 00:43:33.925508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fcba7695ea9'
down_revision: Union[str, Sequence[str], None] = '6dca5ff20c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgao',
    sa.Column('telefone', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', name='status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipe_manutencao',
    sa.Column('id_orgao', sa.UUID(), nullable=False),
    sa.Column('especialidade', sa.Text(), nullable=False),
    sa.Column('quantidade_membros', sa.SMALLINT(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', name='status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_orgao'], ['orgao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocorrencia',
    sa.Column('id_obstaculo', sa.UUID(), nullable=False),
    sa.Column('id_cidadao', sa.UUID(), nullable=False),
    sa.Column('id_orgao', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', name='status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_cidadao'], ['cidadao.id'], ),
    sa.ForeignKeyConstraint(['id_obstaculo'], ['obstaculo.id'], ),
    sa.ForeignKeyConstraint(['id_orgao'], ['orgao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagem',
    sa.Column('id_ocorrencia', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', name='status', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_ocorrencia'], ['ocorrencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vistoria',
    sa.Column('id_ocorrencia', sa.UUID(), nullable=False),
    sa.Column('id_fiscal', sa.UUID(), nullable=False),
    sa.Column('laudo', sa.Text(), nullable=False),
    sa.Column('prazo_adequacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', name='status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_fiscal'], ['fiscal.id'], ),
    sa.ForeignKeyConstraint(['id_ocorrencia'], ['ocorrencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervencao',
    sa.Column('id_vistoria', sa.UUID(), nullable=False),
    sa.Column('id_equipe', sa.UUID(), nullable=False),
    sa.Column('custo_estimado', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('data_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', name='status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_equipe'], ['equipe_manutencao.id'], ),
    sa.ForeignKeyConstraint(['id_vistoria'], ['vistoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('bairro', 'status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', name='status', native_enum=False),
               existing_nullable=False)
    op.alter_column('cidadao', 'status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', name='status', native_enum=False),
               existing_nullable=False)
    op.alter_column('fiscal', 'status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', name='status', native_enum=False),
               existing_nullable=False)
    op.alter_column('obstaculo', 'status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', name='status', native_enum=False),
               existing_nullable=False)
    op.alter_column('rua', 'status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', name='status', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rua', 'status',
               existing_type=sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', name='status', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.alter_column('obstaculo', 'status',
               existing_type=sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', name='status', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.alter_column('fiscal', 'status',
               existing_type=sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', name='status', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.alter_column('cidadao', 'status',
               existing_type=sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', name='status', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.alter_column('bairro', 'status',
               existing_type=sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', name='status', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.drop_table('intervencao')
    op.drop_table('vistoria')
    op.drop_table('imagem')
    op.drop_table('ocorrencia')
    op.drop_table('equipe_manutencao')
    op.drop_table('orgao')
    # ### end Alembic commands ###
