"""start

Revision ID: 6dca5ff20c43
Revises: 
Create Date: 2026-05-19 23:26:34.082129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dca5ff20c43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bairro',
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cidadao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('fiscal',
    sa.Column('matricula', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('rua',
    sa.Column('id_bairro', sa.UUID(), nullable=False),
    sa.Column('cep', sa.CHAR(length=36), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_bairro'], ['bairro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obstaculo',
    sa.Column('pavimentacao', sa.Enum('BURACO_PISTA', 'BURACO_CALCADA', 'RACHADURA_ASFALTO', 'CALCADA_DANIFICADA', 'OBRA_ABANDONADA', 'OUTROS', name='problemapavimentacao', native_enum=False), nullable=True),
    sa.Column('iluminacao', sa.Enum('POSTE_QUEBRADO', 'LAMPADA_APAGADA', 'LAMPADA_ACESSA_DIA', 'FIACAO_EXPOSTA', 'OUTROS', name='problemailuminacao', native_enum=False), nullable=True),
    sa.Column('saneamento', sa.Enum('BUEIRO_ENTUPIDO', 'BUEIRO_SEM_TAMPA', 'VAZAMENTO_AGUA', 'VAZAMENTO_ESGOTO', 'OUTROS', name='problemasaneamento', native_enum=False), nullable=True),
    sa.Column('zeladoria', sa.Enum('LIXO_ACUMULADO', 'ARVORE_RISCO_QUEDA', 'GALHOS_INVASIVOS', 'SINALIZACAO_DANIFICADA', 'OUTROS', name='problemazeladoria', native_enum=False), nullable=True),
    sa.Column('id_rua', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.CheckConstraint('(pavimentacao IS NOT NULL)::int + (iluminacao IS NOT NULL)::int + (saneamento IS NOT NULL)::int + (zeladoria IS NOT NULL)::int = 1', name='ckeck_apenas_um_tipo_de_problema'),
    sa.ForeignKeyConstraint(['id_rua'], ['rua.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obstaculo')
    op.drop_table('rua')
    op.drop_table('fiscal')
    op.drop_table('cidadao')
    op.drop_table('bairro')
    # ### end Alembic commands ###
