"""add indices

Revision ID: e0b0b8145bcc
Revises: 4fcba7695ea9
Create Date: 2026-05-20 20:08:05.030295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0b0b8145bcc'
down_revision: Union[str, Sequence[str], None] = '4fcba7695ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ocorrencia_obstaculo_data', 'ocorrencia', ['id_obstaculo', 'created_at'], unique=False)
    op.create_index(op.f('ix_rua_id_bairro'), 'rua', ['id_bairro'], unique=False)
    op.create_index(op.f('ix_vistoria_id_ocorrencia'), 'vistoria', ['id_ocorrencia'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vistoria_id_ocorrencia'), table_name='vistoria')
    op.drop_index(op.f('ix_rua_id_bairro'), table_name='rua')
    op.drop_index('idx_ocorrencia_obstaculo_data', table_name='ocorrencia')
    # ### end Alembic commands ###
