-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.alembic_version
(
    version_num character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

CREATE TABLE IF NOT EXISTS public.bairro
(
    nome text COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default",
    id uuid NOT NULL,
    status character varying(8) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT bairro_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cidadao
(
    id uuid NOT NULL,
    status character varying(8) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    senha character varying(200) COLLATE pg_catalog."default" NOT NULL,
    nome text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cidadao_pkey PRIMARY KEY (id),
    CONSTRAINT cidadao_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.equipe_manutencao
(
    id_orgao uuid NOT NULL,
    especialidade text COLLATE pg_catalog."default" NOT NULL,
    quantidade_membros smallint NOT NULL,
    id uuid NOT NULL,
    status character varying(8) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    nome text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT equipe_manutencao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.fiscal
(
    matricula character varying(16) COLLATE pg_catalog."default" NOT NULL,
    id uuid NOT NULL,
    status character varying(8) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    senha character varying(200) COLLATE pg_catalog."default" NOT NULL,
    nome text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT fiscal_pkey PRIMARY KEY (id),
    CONSTRAINT fiscal_email_key UNIQUE (email),
    CONSTRAINT fiscal_matricula_key UNIQUE (matricula)
);

CREATE TABLE IF NOT EXISTS public.imagem
(
    id_ocorrencia uuid NOT NULL,
    status character varying(8) COLLATE pg_catalog."default" NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT imagem_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.intervencao
(
    id_vistoria uuid NOT NULL,
    id_equipe uuid NOT NULL,
    custo_estimado numeric(10, 2) NOT NULL,
    data_registro timestamp with time zone NOT NULL DEFAULT now(),
    data_conclusao timestamp with time zone,
    id uuid NOT NULL,
    status character varying(8) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    descricao text COLLATE pg_catalog."default",
    CONSTRAINT intervencao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.obstaculo
(
    pavimentacao character varying(18) COLLATE pg_catalog."default",
    iluminacao character varying(18) COLLATE pg_catalog."default",
    saneamento character varying(16) COLLATE pg_catalog."default",
    zeladoria character varying(22) COLLATE pg_catalog."default",
    id_rua uuid NOT NULL,
    id uuid NOT NULL,
    status character varying(8) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    descricao text COLLATE pg_catalog."default",
    CONSTRAINT obstaculo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ocorrencia
(
    id_obstaculo uuid NOT NULL,
    id_cidadao uuid NOT NULL,
    id_orgao uuid NOT NULL,
    id uuid NOT NULL,
    status character varying(8) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    descricao text COLLATE pg_catalog."default",
    CONSTRAINT ocorrencia_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orgao
(
    telefone character varying(10) COLLATE pg_catalog."default" NOT NULL,
    id uuid NOT NULL,
    status character varying(8) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    nome text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT orgao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.rua
(
    id_bairro uuid NOT NULL,
    cep character(36) COLLATE pg_catalog."default" NOT NULL,
    nome text COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default",
    id uuid NOT NULL,
    status character varying(8) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT rua_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vistoria
(
    id_ocorrencia uuid NOT NULL,
    id_fiscal uuid NOT NULL,
    laudo text COLLATE pg_catalog."default" NOT NULL,
    prazo_adequacao timestamp with time zone NOT NULL DEFAULT now(),
    id uuid NOT NULL,
    status character varying(8) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    descricao text COLLATE pg_catalog."default",
    CONSTRAINT vistoria_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.equipe_manutencao
    ADD CONSTRAINT equipe_manutencao_id_orgao_fkey FOREIGN KEY (id_orgao)
    REFERENCES public.orgao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.imagem
    ADD CONSTRAINT imagem_id_ocorrencia_fkey FOREIGN KEY (id_ocorrencia)
    REFERENCES public.ocorrencia (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.intervencao
    ADD CONSTRAINT intervencao_id_equipe_fkey FOREIGN KEY (id_equipe)
    REFERENCES public.equipe_manutencao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.intervencao
    ADD CONSTRAINT intervencao_id_vistoria_fkey FOREIGN KEY (id_vistoria)
    REFERENCES public.vistoria (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.obstaculo
    ADD CONSTRAINT obstaculo_id_rua_fkey FOREIGN KEY (id_rua)
    REFERENCES public.rua (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ocorrencia
    ADD CONSTRAINT ocorrencia_id_cidadao_fkey FOREIGN KEY (id_cidadao)
    REFERENCES public.cidadao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ocorrencia
    ADD CONSTRAINT ocorrencia_id_obstaculo_fkey FOREIGN KEY (id_obstaculo)
    REFERENCES public.obstaculo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ocorrencia
    ADD CONSTRAINT ocorrencia_id_orgao_fkey FOREIGN KEY (id_orgao)
    REFERENCES public.orgao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rua
    ADD CONSTRAINT rua_id_bairro_fkey FOREIGN KEY (id_bairro)
    REFERENCES public.bairro (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_rua_id_bairro
    ON public.rua(id_bairro);


ALTER TABLE IF EXISTS public.vistoria
    ADD CONSTRAINT vistoria_id_fiscal_fkey FOREIGN KEY (id_fiscal)
    REFERENCES public.fiscal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vistoria
    ADD CONSTRAINT vistoria_id_ocorrencia_fkey FOREIGN KEY (id_ocorrencia)
    REFERENCES public.ocorrencia (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_vistoria_id_ocorrencia
    ON public.vistoria(id_ocorrencia);

END;